version: "3"
services:

  angular-app:
    container_name: angular-app
    image: skander25/alpine:0.0.1-ANGULAR
    restart: always
    ports:
      - 8086:80
    depends_on:
      - springboot-app
      - mysqldb


  springboot-app:

      image: skander25/alpine:0.0.1-SPRING
      restart: always
      build: .
      ports:
        - 8066:8089
      environment:
        MYSQL_HOST: mysqldb
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_PORT: 3306
  mysqldb:
      container_name: mysqldb
      image: mysql
      volumes:
        - /home/user/Desktop/db:/var/lib/mysql
      ports:
        - 3307:3306
      environment:
        MYSQL_DATABASE: kaddemdb
        MYSQL_ROOT_PASSWORD: root

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    ports:
      - 8087:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
